CREATE TABLE IT_MEMBER (
 NUM INT
 , NAME VARCHAR(10)
 , COURSE_NO INT
);
INSERT INTO IT_MEMBER VALUES (1, 'AA', 1);
INSERT INTO IT_MEMBER VALUES (2, 'BB', 1);
INSERT INTO IT_MEMBER VALUES (3, 'CC', 2);
INSERT INTO IT_MEMBER VALUES (4, 'DD', 2);
INSERT INTO IT_MEMBER VALUES (5, 'EE', 4);
INSERT INTO IT_MEMBER VALUES (6, 'FF', NULL);


CREATE TABLE COURSE02 (
 COURSE_NO INT
 , COURSE_NAME VARCHAR(20)
);
INSERT INTO COURSE02 VALUES (1, 'DIGITAL');
INSERT INTO COURSE02 VALUES (2, 'BIG DATA');
INSERT INTO COURSE02 VALUES (3, 'CLOUD');
INSERT INTO COURSE02 VALUES (4, 'NFC');

COMMIT;

/**/
SELECT i.NUM, i.NAME, i.COURSE_NO, c.COURSE_NAME
FROM IT_MEMBER i join COURSE02  c
ON i.COURSE_NO = c.COURSE_NO;

SELECT i.NUM, i.NAME, i.COURSE_NO, c.COURSE_NAME
FROM IT_MEMBER i right outer join COURSE02  c
ON i.COURSE_NO = c.COURSE_NO;


SELECT i.NUM, i.NAME, c.COURSE_NO, c.COURSE_NAME
FROM IT_MEMBER i right outer join COURSE02  c
ON i.COURSE_NO = c.COURSE_NO;

SELECT i.NUM, i.NAME, i.COURSE_NO, c.COURSE_NAME
FROM IT_MEMBER i right outer join COURSE02  c
ON i.COURSE_NO = c.COURSE_NO;


SELECT i.NUM, i.NAME, c.COURSE_NO, c.COURSE_NAME
FROM IT_MEMBER i left outer join COURSE02  c
ON i.COURSE_NO = c.COURSE_NO;
